<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GumBridge.Contracts/GumBridge.Contracts.csproj" />
    <ProjectReference Include="../GumBridge.Conversion/GumBridge.Conversion.csproj" />
  </ItemGroup>
</Project>
